title: "Kamal"
description: "Deploy web apps anywhere"
url: https://kamal-deploy.org
image: /assets/images/opengraph.png
github: basecamp
repository: basecamp/kamal-site
markdown: kramdown
highlighter: rouge

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: compressed

collections:
  docs:
    output: true
    permalink: /docs/:name

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: docs

redirect_from:
  json: false
